# Generated by Django 4.2.5 on 2023-09-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookstore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
