# Generated by Django 4.2.5 on 2023-09-21 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookstore", "0002_book_price"),
    ]

    operations = []
