# Generated by Django 4.2.5 on 2023-09-21 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookstore", "0003_remove_book_font_delete_font"),
    ]

    operations = [
        migrations.RunSQL(
            # Copy-pasted from sqlmigrate on migration 0003 without
            # SeparateDatabaseAndState.
            """
            --
            -- Remove field font from book
            --
            CREATE TABLE "new__bookstore_book" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(1023) NOT NULL, "description" text NOT NULL, "pages" integer NOT NULL, "isbn" integer NULL, "price" decimal NULL);
            INSERT INTO "new__bookstore_book" ("id", "title", "description", "pages", "isbn", "price") SELECT "id", "title", "description", "pages", "isbn", "price" FROM "bookstore_book";
            DROP TABLE "bookstore_book";
            ALTER TABLE "new__bookstore_book" RENAME TO "bookstore_book";
            --
            -- Delete model Font
            --
            DROP TABLE "bookstore_font";
            """,
        ),
    ]
